@startuml
'https://plantuml.com/sequence-diagram
class ListApp{
+Main
+start
}
class ListAppController{
-listTextBox
-taskIDText
-newDueDate
-newDescription
-taskDueDateText
-taskDescriptionText
-clearList



+addTaskClicked
+displayTasks
+editTaskClicked
+removeTaskClicked
+clearList



}

class Operations{
-task: List<Task>

+addTasks
+returnTaskDesc
+returnTaskDueDate: String
editTask
+deleteTask
+displayList: List<String>
+clearList
}

class Task {
-Description: String
-DueDate: String
}

ListAppController - Operations
Task --* Operations
@enduml